title: Ali Ashraf
logo: /assets/img/img_profile.png
description: Senior Android Developer
show_downloads: true
theme: jekyll-theme-cayman

author:
  name: Ali Ashraf
  email: sifyanali739@gmail.com
  avatar: /assets/img/img_profile.png
