title: Ali Ashraf
description: Senior Android Developer
theme: jekyll-theme-cayman
url: "https://yourusername.github.io"
baseurl: ""

author:
  name: Your Name
  email: sifyanali739@gmail.com
  avatar: /assets/profile.jpg